# Generated by Django 3.1.5 on 2022-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
