# Generated by Django 3.1.5 on 2022-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221208_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('O', 'Options'), ('F', 'Future'), ('E', 'Equity')], default='', max_length=2),
        ),
    ]
