# Generated by Django 3.1.5 on 2022-12-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Options',
        ),
    ]
